CREATE TABLE PROCESSLOCK (
	PROCESSNAME VARCHAR2(256) NOT NULL,
	HOSTNAME VARCHAR2(256) NOT NULL,
	PROCESSSEQID NUMBER(20),
	LOCKSTARTTIME TIMESTAMP,
	PRIMARY KEY (PROCESSNAME, HOSTNAME),
	FOREIGN KEY (PROCESSSEQID)
      REFERENCES PROCESS (PROCESSSEQID)
);

COMMENT ON TABLE PROCESSLOCK IS 'Table to provide lock to one instance of process across all hosts.';
COMMENT ON COLUMN PROCESSLOCK.PROCESSNAME IS 'Name of process/thread/engine to get lock for';
COMMENT ON COLUMN PROCESSLOCK.PROCESSSEQID IS 'Process id which owns this lock.';
COMMENT ON COLUMN PROCESSLOCK.HOSTNAME IS 'Host where this process is running';
COMMENT ON COLUMN PROCESSLOCK.LOCKSTARTTIME IS 'Time when this lock is acquire for process';

CREATE OR REPLACE PUBLIC SYNONYM PROCESSLOCK FOR PROCESSLOCK;