CREATE TABLE SAIX_AUTH.PROCESSLOCK (
	PROCESSNAME VARCHAR2(256) NOT NULL,
	HOSTNAME VARCHAR2(256) NOT NULL,
	PROCESSSEQID NUMBER(20),
	LOCKSTARTTIME TIMESTAMP WITH time zone,
	PRIMARY KEY (PROCESSNAME, HOSTNAME),
	FOREIGN KEY (PROCESSSEQID)
      REFERENCES SAIX_AUTH.PROCESS (PROCESSSEQID)
);

COMMENT ON TABLE SAIX_AUTH.PROCESSLOCK IS 'Table to provide lock to one instance of process across all hosts.';
COMMENT ON COLUMN SAIX_AUTH.PROCESSLOCK.PROCESSNAME IS 'Name of process/thread/engine to get lock for';
COMMENT ON COLUMN SAIX_AUTH.PROCESSLOCK.PROCESSSEQID IS 'Process id which owns this lock.';
COMMENT ON COLUMN SAIX_AUTH.PROCESSLOCK.HOSTNAME IS 'Host where this process is running';
COMMENT ON COLUMN SAIX_AUTH.PROCESSLOCK.LOCKSTARTTIME IS 'Time when this lock is acquire for process';

